"""add one-to-one relationship between Students and StudentProfile

Revision ID: cbc4fe2f173d
Revises: 0e81cb71a639
Create Date: 2025-08-10 12:51:37.768501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc4fe2f173d'
down_revision: Union[str, None] = '0e81cb71a639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('student_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'student_profiles', ['student_id'])
    op.create_foreign_key(None, 'student_profiles', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='unique')
    op.drop_column('student_profiles', 'student_id')
    # ### end Alembic commands ###
